/* Option */
export const OPTION_CHANGE = "OPTION_CHANGE";
export const OPTION_LOAD = "OPTION_LOAD";
export const OPTION_LOAD_SUCCESS = "OPTION_LOAD_SUCCESS";
export const OPTION_LOAD_FAILURE = "OPTION_LOAD_FAILURE";

/* Option info */
export const OPTION_INFO_LOAD = "OPTION_INFO_LOAD";
export const OPTION_INFO_LOAD_SUCCESS = "OPTION_INFO_LOAD_SUCCESS";
export const OPTION_INFO_LOAD_FAILURE = "OPTION_INFO_LOAD_FAILURE";

/* Lang */
export const SET_LANG = "SET_LANG";
