/* Option */
export const OPTION_CHANGE = "OPTION_CHANGE";
export const OPTION_LOAD = "OPTION_LOAD";
export const OPTION_LOAD_SUCCESS = "OPTION_LOAD_SUCCESS";
export const OPTION_LOAD_FAILURE = "OPTION_LOAD_FAILURE";

